# Generated by Django 3.2.10 on 2022-05-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('idCancion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de cancion')),
                ('nombreCancion', models.CharField(max_length=20, verbose_name='Nombre de la cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de imagen')),
                ('rutaImagen', models.CharField(max_length=50, verbose_name='Ruta imagen')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youmusic.cancion')),
            ],
        ),
    ]
