# Generated by Django 3.2.10 on 2022-05-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='rutaImagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='img', upload_to='img'),
        ),
    ]
