# Generated by Django 3.2.10 on 2022-05-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0002_auto_20220510_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='nombreImagen',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre Imagen Cancion'),
        ),
    ]
