# Generated by Django 3.2.10 on 2022-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0006_auto_20220516_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='cancion',
            field=models.FileField(default='youmusic/files/audio', upload_to='youmusic/files/audio'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='youmusic/files/img', upload_to='youmusic/files/img'),
        ),
    ]
