# Generated by Django 3.2.10 on 2022-05-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0008_auto_20220516_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='cancion',
            field=models.FileField(default='static\\youmusic\x07udio', upload_to='static\\youmusic\x07udio'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='static\\youmusic\\img\\music-img', upload_to='static\\youmusic\\img\\music-img'),
        ),
    ]
