# Generated by Django 3.2.10 on 2022-05-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0010_auto_20220516_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='imagen',
        ),
    ]
