# Generated by Django 3.2.10 on 2022-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0013_auto_20220518_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='cancion',
            field=models.FileField(upload_to='static/youmusic/files'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(upload_to='static/youmusic/files'),
        ),
    ]
