# Generated by Django 3.2.10 on 2022-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0014_auto_20220518_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='cancion',
            name='audioCancion',
            field=models.FileField(default='static/youmusic/files', upload_to='static/youmusic/files', verbose_name='Audio Cancion'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='imagenCancion',
            field=models.ImageField(default='static/youmusic/files', upload_to='static/youmusic/files', verbose_name='Imagen Cancion'),
        ),
    ]
