# Generated by Django 3.2.10 on 2022-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0015_auto_20220518_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='audioCancion',
            field=models.FileField(default='/', upload_to='static/youmusic/files', verbose_name='Audio Cancion'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagenCancion',
            field=models.ImageField(default='/', upload_to='static/youmusic/files', verbose_name='Imagen Cancion'),
        ),
    ]
