# Generated by Django 3.2.10 on 2022-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0017_auto_20220618_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='Nombre de Usuario')),
                ('contraseñaUsuario', models.CharField(max_length=30, verbose_name='Contraseña de Usuario')),
                ('tokenUsuario', models.CharField(max_length=100, verbose_name='Token de Usuario')),
                ('emailUsuario', models.CharField(max_length=100, null=True, verbose_name='Email de Usuario')),
            ],
        ),
    ]
