# Generated by Django 3.2.10 on 2022-06-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youmusic', '0018_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
